### ISSUE TITLE
Check fails commit hooks on windows machines

### ISSUE THREAD

**Issue by morganr1** [mlennox/pull-request-size-reminder#8]
Client info:
- Windows 10 @latest
- NPM 6.4.1
- Node 10.15.3
- Power shell used too (cygwin)

See below the stack trace. 

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'check-pr-size' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'precheck-pr-size', 'check-pr-size', 'postcheck-pr-size' ]
5 info lifecycle xxx@0.16.4~precheck-pr-size: xxx@0.16.4
6 info lifecycle xxx@0.16.4~check-pr-size: xxx@0.16.4
7 verbose lifecycle xxx@0.16.4~check-pr-size: unsafe-perm in lifecycle true
8 verbose lifecycle xxx@0.16.4~check-pr-size: PATH: xxxxx
10 silly lifecycle xxx@0.16.4~check-pr-size: Args: [ '/d /s /c', 'pull-request-size-reminder' ]
11 silly lifecycle xxx@0.16.4~check-pr-size: Returned: code: 1  signal: null
12 info lifecycle xxx@0.16.4~check-pr-size: Failed to exec check-pr-size script
13 verbose stack Error: xxx@0.16.4 check-pr-size: `pull-request-size-reminder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\username\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid xxx@0.16.4
15 verbose cwd C:\Users\username\Documents\ovProj\CareTeamWebApp
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "check-pr-size"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error xxx@0.16.4 check-pr-size: `pull-request-size-reminder`
22 error Exit status 1
23 error Failed at the xxx@0.16.4 check-pr-size script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

any other needed details do let me know :)

**Comment by mlennox** [comment]
can you run 

```
echo %COMSPEC%
```

in the terminal used for development on the windows machines?

Also, can you check if the following git command works in the same terminal on windows

```
git --no-pager diff --cached --stat $(git merge-base FETCH_HEAD origin)
```

**Comment by mlennox** [comment]
Further investigation showed that Windows git has an issue with the CLI options.

I intend to fix this by using an npm library that abstracts the GIT command.

**Comment by mlennox** [comment]
@morganr1 I've published a new version - 1.0.11 - can you get someone to check the package on the problem laptop and let me know if it works?

**Comment by morganr1** [comment]
will follow up shortly and let you know

**Comment by morganr1** [comment]
Hey,

This is the error log he got from trying the latest version of the npm package. May or may not be useful to you...

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'check-pr-size' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'precheck-pr-size', 'check-pr-size', 'postcheck-pr-size' ]
5 info lifecycle careteam-web-app@0.16.4~precheck-pr-size: careteam-web-app@0.16.4
6 info lifecycle careteam-web-app@0.16.4~check-pr-size: careteam-web-app@0.16.4
7 verbose lifecycle careteam-web-app@0.16.4~check-pr-size: unsafe-perm in lifecycle true
8 verbose lifecycle careteam-web-app@0.16.4~check-pr-size: PATH: C:\Users\mokeefe\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\mokeefe\Documents\ovProj\CareTeamWebApp\node_modules\.bin;C:\Users\mokeefe\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\mokeefe\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Flyway\flyway-5.0.7;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\GitExtensions;C:\bin;C:\Users\ifitzgerald\AppData\Local\Programs\Python\Python36;C:\Oneview\ClinicalUIAutomation\ClinicalUIAutomationRobotFramework;C:\Program Files\Git\cmd;C:\Users\mokeefe\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Users\mokeefe\AppData\Local\Microsoft\WindowsApps;C:\Users\mokeefe\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mokeefe\AppData\Roaming\npm;C:\Users\mokeefe\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\mokeefe\AppData\Local\Yarn\bin;C:\Users\mokeefe\AppData\Local\Programs\Python\Python38-32;C:\Users\mokeefe\AppData\Local\Programs\Python\Python38-32\Scripts;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle careteam-web-app@0.16.4~check-pr-size: CWD: C:\Users\mokeefe\Documents\ovProj\CareTeamWebApp
10 silly lifecycle careteam-web-app@0.16.4~check-pr-size: Args: [ '/d /s /c', 'pull-request-size-reminder' ]
11 silly lifecycle careteam-web-app@0.16.4~check-pr-size: Returned: code: 1  signal: null
12 info lifecycle careteam-web-app@0.16.4~check-pr-size: Failed to exec check-pr-size script
13 verbose stack Error: careteam-web-app@0.16.4 check-pr-size: `pull-request-size-reminder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\mokeefe\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\mokeefe\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid careteam-web-app@0.16.4
15 verbose cwd C:\Users\mokeefe\Documents\ovProj\CareTeamWebApp
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "check-pr-size"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error careteam-web-app@0.16.4 check-pr-size: `pull-request-size-reminder`
22 error Exit status 1
23 error Failed at the careteam-web-app@0.16.4 check-pr-size script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by mlennox** [comment]
Closing this issue now as it has been working in a development house on a range of machines - happy to open it again if you find an issue.
